"""
Django settings for example project.

Generated by 'django-admin startproject' using Django 1.9.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'qwxc8vysg$sg0w4b+dhp=qcipcv6m@4b-ej3sdy!4feb@$eo$x'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

SITE_ID=1
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.sitemaps',
    'blog',
    'taggit',
]

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'example.urls'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'example.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'exampledb',
        'USER':'root',
        'HOST':'127.0.0.1',
        'PORT':'3306',
        'PASSWORD':'root',
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

MEDIA_URL='/upload/'
MEDIA_ROOT=os.path.join(BASE_DIR+'upload/')
STATIC_URL = '/static/'
STATIC_ROOT='/static/'
STATICFILES_DIRS=(os.path.join(BASE_DIR, 'static'),)
'''The STATICFILES_DIRS tuple tells Django where to look for static files that are not tied to a particular app. In this case, we just told Django to also look for static files in a folder called static in our root folder, not just in our apps. '''

##################################################################################

# EMAIL_HOST = 'smtp.mailgun.org'
# EMAIL_HOST_USER = 'support@padoliko.com'
# EMAIL_HOST_PASSWORD = '_devendra_'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True

#EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'


API_KEY='key-22633f890d0543eb2f9a045dd1126e88'#PRIVATE

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_FROM = 'info@padoliko.com'

EMAIL_HOST='smtp.mailgun.org'
EMAIL_PORT='587'
EMAIL_HOST_USER='info@padoliko.com'#support@padoliko.com'#blank
EMAIL_HOST_PASSWORD='dev@ravi'
EMAIL_USE_TLS=True
EMAIL_USE_SSL=False

SITE_DOMAIN = "www.padoliko.com"


#settings for mail firing

API_KEY='key-22633f890d0543eb2f9a045dd1126e88'#PRIVATE

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_FROM = 'info@padoliko.com'

EMAIL_HOST='smtp.mailgun.org'
EMAIL_PORT='587'
EMAIL_HOST_USER='info@padoliko.com'#support@padoliko.com'#blank
EMAIL_HOST_PASSWORD='dev@ravi'
EMAIL_USE_TLS=True
EMAIL_USE_SSL=False