# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-10 16:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('admin', '0002_logentry_remove_auto_add'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('query', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL, unique=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('about_author', models.TextField(max_length=100)),
                ('photo', models.ImageField(blank=True, upload_to='upload/users/%Y/%m/%d')),
            ],
        ),
        migrations.RemoveField(
            model_name='author',
            name='user_ptr',
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to='blog.Profile'),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
